bar:
  location: top
  height: 32
  background: 11111bff
  margin: 5
  spacing: 10
  font: "JetBrainsMono Nerd Font:style=Bold:size=11"

  left:
    - script:
        path: /home/sword/.config/yambar/ws
        content:
          string:
            text: "{workspaces}"
            foreground: cdd6f4ff
            deco:
              stack:
                - background: {color: 313244ff}
                - border:
                    color: 45475aff
                    width: 1
                    rounded-corners: 12

  center:
    - clock:
        content:
          string:
            text: "{time}"
            foreground: bac2deff
            deco:
              stack:
                - background: {color: 313244ff}
                - border:
                    color: 45475aff
                    width: 1
                    rounded-corners: 12

  right:
    - cpu:
        poll-interval: 3000
        content:
          map:
            conditions:
              id == -1:
                string:
                  text: " ï’¼ {usage}% "
                  foreground: a6e3a1ff
                  deco:
                    stack:
                      - background: {color: 313244ff}
                      - border:
                          color: 45475aff
                          width: 1
                          rounded-corners: 12
